### ISSUE TITLE
Please add your results on paperswithcode.com 

### ISSUE THREAD

**Issue by LifeIsStrange** [husthuaan/AoANet#1]
Paperswithcode.com is the reference for state of the art visibility.

Someone did submit your paper but please submit your results on tested tasks. 
https://paperswithcode.com/paper/attention-on-attention-for-image-captioning

https://paperswithcode.com/sota/object-detection-on-coco
Well I don't know if MS coco is a different dataset than coco, if so please submit Ms coco on paperswithcode.com. 

Please submit it too to the real MS coco leaderboard
http://cocodataset.org/#captions-leaderboard

**Comment by husthuaan** [comment]
The results were submitted to https://competitions.codalab.org/competitions/3221#results, but got removed by this site somehow. And we will re-submit.
