### ISSUE TITLE
regarding scores of XE

### ISSUE THREAD

**Issue by fawazsammani** [husthuaan/AoANet#13]
Hello. Thanks for your code!
I would like to ask about the difference between the results you posted on GitHub and in the paper. We're actually comparing your results with ours for our new work, so it would be useful to know the exact results. For your single model under XE, you reported the BLEU-4 as 37.2, but in your GitHub page, it is reported as 36.9. For your cider score, you reported in the paper as 119.8 but in your GitHub it's 118.4. So May we please know which ones are correct?

Regards
Wish you all the best in your ICCV presentation!

**Comment by husthuaan** [comment]
Please refer to the scores reported in the paper.
Sorry for the difference. The code in this repo has been re-organized. The results posted here are from a random model trained using this code.
It's hard to produce the identical scores when training for a second time: some of them become higher while the others become lower.

**Comment by fawazsammani** [comment]
I do understand. It seems that the results reported in the paper is from the best model of your 5 ensembles. Thanks for the info. Regards

**Comment by husthuaan** [comment]
You are right. It is selected from the best model regarding the Cider score.

**Comment by fawazsammani** [comment]
Hi @husthuaan . Regarding the issue previously opened, I will need the scores of your particular pre-trained model that you uploaded on GitHub. Are the scores for that model same as you posted for XE? (below are the ones you posted). 
`{'Bleu_1': 0.7729384559899702, 'Bleu_2': 0.6163398035383025, 'Bleu_3': 0.4790123137715982, 'Bleu_4': 0.36944349063530374, 'METEOR': 0.2848188431924821, 'ROUGE_L': 0.5729849683867054, 'CIDEr': 1.1842173801790759, 'SPICE': 0.21650786258302354}`

Thanks in advance!

**Comment by husthuaan** [comment]
@fawazsammani  Yes.
