### ISSUE TITLE
Can't reproduce your metrics accuracy

### ISSUE THREAD

**Issue by wyong16** [husthuaan/AoANet#14]
I did run this code, but got Bleu4 :0.362  CiderD:1.155, which is much lower than yours 0.36944, 1.184. Have i missed something?

**Comment by wyong16** [comment]
I just set do_aoa=1 on line 153(AoAModel), and run the script. Are there other hyper params should be set?

**Comment by husthuaan** [comment]
Did you get these scores after making this change?
You should keep the code as it is. `do_aoa` is set to 0 because there is an `AoA` layer after the attention.

**Comment by wyong16** [comment]
I have tried both, but it got little difference.

**Comment by husthuaan** [comment]
Maybe it's because of the difference in vocabulary.
The default value of `word_count_threshold` in `scripts/prepro_labels.py` is 5, and it results in a smaller vocabulary.
Set `word_count_threshold` to 4, and you will a vocabulary of size 10369.
Please inform me if you still can't reproduce the results.

**Comment by husthuaan** [comment]
Did you use the evaluation script to get the results, i.e. using beam search and on the test split?

**Comment by wyong16** [comment]
Which word_count_threshold did you use in your experiment to get the best result? 4? 
In my experiment, I use beam size=2 in test split.

**Comment by husthuaan** [comment]
It's 4 in our experiments.

**Comment by wyong16** [comment]
Thanks a lot, I will have a try!

**Comment by wyong16** [comment]
It doesn't work to enlarge vocabulary! One more thing to say, to accelerate training, My batch_size is 200 or 400, but I think it's not the real reason. Any other suggestions?

**Comment by husthuaan** [comment]
Batch size does influence the accuracy.
You have to tune other hyper params as well if you enlarge batch size, such as lr schedule, dropout rate, training epochs and etc.

**Comment by fawazsammani** [comment]
@husthuaan Do you think the vocabulary size matters? Even if the vocavulary increases (more weights in the output layer), if the weights for the OOV words won't really get updated in the backward pass, so it does not affect i believe?

**Comment by husthuaan** [comment]
@fawazsammani I don't think it matters too much, but I am not sure.

**Comment by fjqfjqfjqfjqfjqfjqfjq** [comment]
> It doesn't work to enlarge vocabulary! One more thing to say, to accelerate training, My batch_size is 200 or 400, but I think it's not the real reason. Any other suggestions?

I meet the same problem with you. Have you found the reasons?
