### ISSUE TITLE
Performances under XE training

### ISSUE THREAD

**Issue by zhengyi123456** [husthuaan/AoANet#16]
Hi, I noticed that in you readme file, you mentioned using XE training for 25 epochs can get the CIDEr around 118. However, when I tyied to redo your experiments. I only can get the score far lower that 118, like 113. I follow the parameters in you train.sh. Do you have any advice? Thanks.

**Comment by Daic115** [comment]
Maybe you are using fixed bottom-up features , change it to adaptive.

**Comment by zhengyi123456** [comment]
> Maybe you are using fixed bottom-up features , change it to adaptive.

@Daic115  Hi, I am not sure how to make the features adaptive, could you give some details, thanks. By the way, have you successfully redo the performance?

**Comment by zhengyi123456** [comment]
@husthuaan Acutally, I downloaded your opened model trained under XE from google driver, and I can still only get CIDEr 116.9 and BLEU-4 37.1, The scores you mentioned in readme file, did you use ensemble training method?

**Comment by Daic115** [comment]
You should download feature [here](https://github.com/peteanderson80/bottom-up-attention) in section `Pretrained features` .The 'adptive' means 10 to 100 boxes' features per image and 'fixed' means 36 per image.After downloading tsv files,then using `python script/make_bu_data.py --OPTIONS` to get numpy array data.

**Comment by husthuaan** [comment]
@Daic115 Thanks for answering for me.

>  Acutally, I downloaded your opened model trained under XE from google driver, and I can still only get CIDEr 116.9 and BLEU-4 37.1

@zhengyi123456 You are probably using the 'fixed' bottom-up features but we're using the 'adaptive'. I think it's the reason. Try the 'adaptive'.

>  did you use ensemble training method?

All these scores are reported by one single model (in google drive).

**Comment by zhengyi123456** [comment]
@Daic115 @husthuaan  Thank you so much for your help, I never mention the difference between fixed features and unfixed features. Actually, I use the 36 fixed features and I think it might be the reason, I will try to use the unfixed features to redo the performance. Thanks again.
