### ISSUE TITLE
How to get caption results on the COCO test dataset

### ISSUE THREAD

**Issue by homelifes** [husthuaan/AoANet#17]
Hi. Thanks for your work on Attention on Attention for Image Captioning.
May I ask how can I get results on COCO test images (not karpathy split) given that I've extracted the bottom up features of all the 40k images in the COCO test dataset. Because the dataloader.py can only load the karpathy split images (train, val and test) which are all from the official training and validation COCO images, but not the official COCO testing images.

**Comment by husthuaan** [comment]
Sorry for the delay.
Please refer to https://github.com/husthuaan/AoANet/issues/9. It's similar.

**Comment by fawazsammani** [comment]
You can use this code. I've wrote it a few days ago for my own experiments. I have adjusted it for you to fit for this repository. First download the COCO test 2014 images and rename the folder to 'test_images', then run this code to create the cocotalk file for test images:

```
from PIL import Image
import json
import os

cocotalk_dir = 'data/cocotalk.json'
with open(cocotalk_dir, 'r') as c:
    cocotalk = json.load(c)
test_images = os.listdir('test_images')
images = []
for img in test_images:
    tmp = {}
    tmp["split"] = "test"
    tmp["file_path"] = "test2014\\" + str(img)
    image_id = img.split('_')[2]
    image_id = int(image_id.lstrip("0").split('.')[0])
    tmp["id"] = image_id
    with Image.open(os.path.join('test_images', img)) as im:
        tmp['width'], tmp['height'] = im.size
    images.append(tmp)

cocotalk_test = {}
cocotalk_test["ix_to_word"] = cocotalk['ix_to_word']
cocotalk_test["images"] = images

with open('data/cocotalk_test', 'w') as w:
    json.dump(cocotalk_test, w)

```
Hope this helps!
