### ISSUE TITLE
Training under RL

### ISSUE THREAD

**Issue by zhengyi123456** [husthuaan/AoANet#18]
Hi, I downloaded your pretrained model under XE, and train it under RL by myself and using the hyper-parameters you suggested. However, it is hard for my mode to get 128.9 in CIDEr, after training it for around 15 epochs, I can only get CIDEr around 125.8, the training log file I attached below. Did I miss something in my training, could you give me some advice about it, thanks.

Summary Epoch 25 Iteration 285000: CIDEr: 1.20535625974 BLEU-4: 0.374360484694
Summary Epoch 25 Iteration 288000: CIDEr: 1.21644513359 BLEU-4: 0.377511152673
Summary Epoch 25 Iteration 291000: CIDEr: 1.22712429095 BLEU-4: 0.381219736579
Summary Epoch 25 Iteration 294000: CIDEr: 1.22381542914 BLEU-4: 0.382676287478
Summary Epoch 26 Iteration 297000: CIDEr: 1.22245104126 BLEU-4: 0.380970525922
Summary Epoch 26 Iteration 300000: CIDEr: 1.22858843891 BLEU-4: 0.383749147846
Summary Epoch 26 Iteration 303000: CIDEr: 1.23236933926 BLEU-4: 0.384648342135
Summary Epoch 27 Iteration 306000: CIDEr: 1.22778937572 BLEU-4: 0.379421154015
Summary Epoch 27 Iteration 309000: CIDEr: 1.23117294516 BLEU-4: 0.382275991613
Summary Epoch 27 Iteration 312000: CIDEr: 1.22690404811 BLEU-4: 0.377485600055
Summary Epoch 27 Iteration 315000: CIDEr: 1.22596435533 BLEU-4: 0.37656478873
Summary Epoch 28 Iteration 318000: CIDEr: 1.23113680841 BLEU-4: 0.378078049184
Summary Epoch 28 Iteration 321000: CIDEr: 1.22219880254 BLEU-4: 0.376720037449
Summary Epoch 28 Iteration 324000: CIDEr: 1.22450555714 BLEU-4: 0.376878519964
Summary Epoch 28 Iteration 327000: CIDEr: 1.23221814256 BLEU-4: 0.38080060362
Summary Epoch 29 Iteration 330000: CIDEr: 1.23293688594 BLEU-4: 0.379261504259
Summary Epoch 29 Iteration 333000: CIDEr: 1.22761806607 BLEU-4: 0.378923884146
Summary Epoch 29 Iteration 336000: CIDEr: 1.23036486301 BLEU-4: 0.379744772006
Summary Epoch 29 Iteration 339000: CIDEr: 1.2355931814 BLEU-4: 0.383146607728
Summary Epoch 30 Iteration 342000: CIDEr: 1.23970003848 BLEU-4: 0.382621050484
Summary Epoch 30 Iteration 345000: CIDEr: 1.23124142832 BLEU-4: 0.379181716187
Summary Epoch 30 Iteration 348000: CIDEr: 1.23963901563 BLEU-4: 0.381838518731
Summary Epoch 30 Iteration 351000: CIDEr: 1.23712770928 BLEU-4: 0.381104896358
Summary Epoch 31 Iteration 354000: CIDEr: 1.23905327936 BLEU-4: 0.382181405535
Summary Epoch 31 Iteration 357000: CIDEr: 1.23865820759 BLEU-4: 0.380385008518
Summary Epoch 31 Iteration 360000: CIDEr: 1.23890607165 BLEU-4: 0.382158375018
Summary Epoch 32 Iteration 363000: CIDEr: 1.2422573845 BLEU-4: 0.38312280932
Summary Epoch 32 Iteration 366000: CIDEr: 1.24205671884 BLEU-4: 0.380462115168
Summary Epoch 32 Iteration 369000: CIDEr: 1.24448354107 BLEU-4: 0.383820786972
Summary Epoch 32 Iteration 372000: CIDEr: 1.24865813961 BLEU-4: 0.382844818505
Summary Epoch 33 Iteration 375000: CIDEr: 1.24660560748 BLEU-4: 0.382131662751
Summary Epoch 33 Iteration 378000: CIDEr: 1.24911968939 BLEU-4: 0.38147231651
Summary Epoch 33 Iteration 381000: CIDEr: 1.24742752637 BLEU-4: 0.382920547899
Summary Epoch 33 Iteration 384000: CIDEr: 1.24204867569 BLEU-4: 0.380141316284
Summary Epoch 34 Iteration 387000: CIDEr: 1.24467370437 BLEU-4: 0.379317983455
Summary Epoch 34 Iteration 390000: CIDEr: 1.24900948985 BLEU-4: 0.384206565975
Summary Epoch 34 Iteration 393000: CIDEr: 1.24795086987 BLEU-4: 0.382033262338
Summary Epoch 34 Iteration 396000: CIDEr: 1.24795446742 BLEU-4: 0.382549648915
Summary Epoch 35 Iteration 399000: CIDEr: 1.25129004876 BLEU-4: 0.383173313778
Summary Epoch 35 Iteration 402000: CIDEr: 1.24862150197 BLEU-4: 0.381375874739
Summary Epoch 35 Iteration 405000: CIDEr: 1.25521106627 BLEU-4: 0.384039909936
Summary Epoch 36 Iteration 408000: CIDEr: 1.24701270999 BLEU-4: 0.381147354202
Summary Epoch 36 Iteration 411000: CIDEr: 1.24593480853 BLEU-4: 0.381088673188
Summary Epoch 36 Iteration 414000: CIDEr: 1.24249295769 BLEU-4: 0.379374737093
Summary Epoch 36 Iteration 417000: CIDEr: 1.24781981677 BLEU-4: 0.383081090621
Summary Epoch 37 Iteration 420000: CIDEr: 1.25085217982 BLEU-4: 0.38235560786
Summary Epoch 37 Iteration 423000: CIDEr: 1.24786702314 BLEU-4: 0.381571740642
Summary Epoch 37 Iteration 426000: CIDEr: 1.25283589496 BLEU-4: 0.381707295912
Summary Epoch 37 Iteration 429000: CIDEr: 1.25164227751 BLEU-4: 0.381410182478
Summary Epoch 38 Iteration 432000: CIDEr: 1.25029122734 BLEU-4: 0.381370316095
Summary Epoch 38 Iteration 435000: CIDEr: 1.25222712734 BLEU-4: 0.381216232651
Summary Epoch 38 Iteration 438000: CIDEr: 1.25140890676 BLEU-4: 0.381680288211
Summary Epoch 38 Iteration 441000: CIDEr: 1.25159494292 BLEU-4: 0.380607226407
Summary Epoch 39 Iteration 444000: CIDEr: 1.25613250559 BLEU-4: 0.382548820728
Summary Epoch 39 Iteration 447000: CIDEr: 1.25817286469 BLEU-4: 0.383044253677
Summary Epoch 39 Iteration 450000: CIDEr: 1.25836627671 BLEU-4: 0.383209029987
Summary Epoch 39 Iteration 453000: CIDEr: 1.25774123693 BLEU-4: 0.385077146036
Summary Epoch 40 Iteration 456000: CIDEr: 1.25806727932 BLEU-4: 0.384437408663
Summary Epoch 40 Iteration 459000: CIDEr: 1.25752217113 BLEU-4: 0.384869253824
Summary Epoch 40 Iteration 462000: CIDEr: 1.25673376697 BLEU-4: 0.383468184885

**Comment by husthuaan** [comment]
Hi, did you use beam search and evaluate on the test split?

**Comment by zhengyi123456** [comment]
> Hi, did you use beam search and evaluate on the test split? And did you use the vocabulary files provided along with the pretrained model and use these files to generate the cider cache file for RL training?

Hi, I actually evaluate model on test split and I did download the json and h5 file you provided and cahce file is made on it. but I did not use beam search. The results with beam search with beam size == 2 is attached below: {'bad_count_rate': 0.031, 'CIDEr': 1.2588275597588436, 'Bleu_4': 0.38566927959999153, 'Bleu_3': 0.5074083029069282, 'Bleu_2': 0.6529687923972578, 'Bleu_1': 0.8125472093998991, 'ROUGE_L': 0.5890900601767902, 'METEOR': 0.29051756306010657, 'SPICE': 0.22667828926865555} 

It is a little bit better but still far lower than the scores you provided.

**Comment by husthuaan** [comment]
I once used a wrong cache file and got a lower score for Cider and relatively higher scores for other metrics. But it seems not to be the cause of your problem. I don't have any other idea. Could you send me by email your training code and the dataset files of your experiment thus I can investigate it?

**Comment by zhengyi123456** [comment]
> I once used a wrong cache file and got a lower score for Cider and relatively higher scores for other metrics. But it seems not to be the cause of your problem. I don't have any other idea. Could you send me by email your training code and the dataset files of your experiment thus I can investigate it?

Thank you so much for help. I will pack the training code and cache file.
