### ISSUE TITLE
Queries keys and values

### ISSUE THREAD

**Issue by hishamabutt** [husthuaan/AoANet#19]
Can you please explain that what Queries keys and values means in your paper?

**Comment by husthuaan** [comment]
They are the inputs to an attention function.
> An attention function can be described as mapping a query and a set of key-value pairs to an output, where the query, keys, values, and output are all vectors. The output is computed as a weighted sum of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key.

Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N Gomez, Lukasz Kaiser, and Illia Polosukhin. Attention is all you need. In _NeurIPS_, 2017.

**Comment by hishamabutt** [comment]
what are the values of these three in this project? can you explain this project in simple terms? like how do you train the model and how the model is evaluate? and what does cocobu_att, cocobu_fc and coco_box files contain?

**Comment by husthuaan** [comment]
In the encoder, in self-attention, Q, K, V are all projections of A, the feature vectors. In the decoder, Q is a projection of the decoder‘s’ hidden state; K, V are projections of A.
cocobu_att contains A, cocobu_fc contains the mean pooling of A, and coco_box contains the bounding boxes of A.
