### ISSUE TITLE
train loss graph

### ISSUE THREAD

**Issue by hishamabutt** [husthuaan/AoANet#20]
can we get train loss graph from the trained model?

**Comment by husthuaan** [comment]
Yes. You can find the tensorboard log files at https://drive.google.com/open?id=11A095rvPNkaQ7UCMe3sKtkYYpndZ9sg1

**Comment by hishamabutt** [comment]
@husthuaan how can i view or open this files?

**Comment by husthuaan** [comment]
Download it and use tensorboard to view.
