### ISSUE TITLE
why arent you using aoa in the decoder?

### ISSUE THREAD

**Issue by homelifes** [husthuaan/AoANet#21]
Hi. From your paper, you are using AoA in both the encoder and decoder. For the decoder, when you define 
`self.attention = MultiHeadedDotAttention(opt.num_heads, opt.rnn_size, project_k_v=0, scale=opt.multi_head_scale, use_output_layer=0, do_aoa=0, norm_q=1)`
As seen, `do_aoa  = 0`, so its actually not happening in the decoder in this case. 
Is that how it should be?

**Comment by husthuaan** [comment]
It may seem a bit confusing, but there is actually an aoa layer (self.att2ctx) after the attention.  We set `do_aoa = 0` in order to make it easier to compare different decoding schemes.

**Comment by homelifes** [comment]
Oh I see. Thanks!
