### ISSUE TITLE
model relationships

### ISSUE THREAD

**Issue by 2014gaokao** [husthuaan/AoANet#26]
"A refining module is added in the encoder to model relationships of objects in the image." I am very confused about it and where does it represent in the code? thank you.

**Comment by husthuaan** [comment]
Hi @2014gaokao, it's on line 200 in [models/AoAModel.py](https://github.com/husthuaan/AoANet/blob/master/models/AoAModel.py):
`
self.refiner = AoA_Refiner_Core(opt)
`

**Comment by 2014gaokao** [comment]
sorry to disturb you. May I ask what does att_masks mean?

**Comment by 232525** [comment]
@2014gaokao For _adaptive_ (10-100 objects) Bottom-Up features. att_masks=None if you use _fixed_ (36 objects) Bottom-Up features.
