### ISSUE TITLE
questions about AoA operation

### ISSUE THREAD

**Issue by AsuradaYuci** [husthuaan/AoANet#3]
Hi，I am confused about the AoA operation。Assume the dimension of Q is (8, 1024), and the attention result V is (8, 1024) too, So after they **concat**, what's the dimension of QV?.
What's more, I am confused about the  two separate linear transformations to generate an “**information vector**” i and an “**attention gate**” g. I think one linear transformations only has a parameter matrix **W**, but in the paper, there are two parameter matrixs. So how to do the  linear transformations, FC or CONV?
Can you offer me more information about the AoA operation?

**Comment by husthuaan** [comment]
> Hi，I am confused about the AoA operation。Assume the dimension of Q is (8, 1024), and the attention result V is (8, 1024) too, So after they **concat**, what's the dimension of QV?.

The dimension of QV is (8, 2048).

> What's more, I am confused about the two separate linear transformations to generate an “**information vector**” i and an “**attention gate**” g. I think one linear transformations only has a parameter matrix **W**, but in the paper, there are two parameter matrixs. 

Q * W1^T + V * W2^T = [Q, V] * [W1, W2]^T. Let W = [W1, W2], and you can get Q * W1^T + V * W2^T = [Q, V] * W^T, where there is only one parameter matrix W.

> So how to do the linear transformations, FC or CONV?

You can do it using 1x1 CONV. In pytorch, you can directly use nn.Linear.

**Comment by AsuradaYuci** [comment]
@husthuaan Thanks for your reply，I will have a try.
