### ISSUE TITLE
create dataset_coco.json for new dataset

### ISSUE THREAD

**Issue by Tushar-Faroque** [husthuaan/AoANet#31]
Hello,
I want to use AoANet with my own datasets. **dataset_coco.json** is built for MSCOCO.
Is there any way to create the json file for my dataset?

**Comment by husthuaan** [comment]
If you look into the json file, you will see how it's organized, and you can create your own json file in that way.

**Comment by Tushar-Faroque** [comment]
Okay, Thanks
