### ISSUE TITLE
question about the score of CIDEr

### ISSUE THREAD

**Issue by 2014gaokao** [husthuaan/AoANet#33]
你好，我有个问题困扰很久了，就是在github上cider的分数是128.9，论文里是129.8，两者之间差了哪些环节？还有论文里的ensemble的分数是132.0，ensemble和single model之间差了哪些东西？谢谢

**Comment by husthuaan** [comment]
你好，github上的代码是原来实验代码的重新组织，另外代码使用的是随机参数初始化，所以这两次跑的模型的初始化参数不同，最终的分数也有一些差异。ensemble指的是训练多个不同初始化参数的模型，然后将模型每一步输出的词汇表上的概率分布做平均，作为ensemble模型的输出，从而可以减轻模型过拟合的问题，提升分数。具体实现见eval_ensemble.py。
