### ISSUE TITLE
getting error using bottom-up features method 

### ISSUE THREAD

**Issue by faaizhashmi** [husthuaan/AoANet#4]
**while using "python script/make_bu_data.py --output_dir data/cocobu" first i face the error :**

Reading trainval/karpathy_test_resnet101_faster_rcnn_genome.tsv
Traceback (most recent call last):
  File "scripts/make_bu_data.py", line 40, in <module>
    for item in reader:
  File "/home/faaiz/anaconda3/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

**then i changed the line** 
reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES)

**To**
reader = csv.DictReader(tsv_in_file.read().decode('utf-8'), delimiter='\t', fieldnames = FIELDNAMES)

**this resolve the error but then i get this error**

Reading trainval/karpathy_test_resnet101_faster_rcnn_genome.tsv
Traceback (most recent call last):
  File "scripts/make_bu_data.py", line 42, in <module>
    item['num_boxes'] = int(item['num_boxes'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**any suggestions on resolving this error. please help.**

**Comment by fawazsammani** [comment]
Its because your running it on Windows. This script works on Linux only. I'm not sure what to exactly change for Windows OS

**Comment by hishamabutt** [comment]
@fawazsammani we are running it on Linux

**Comment by husthuaan** [comment]
These scripts are originally written for python2, so they might not work well on python3. You might want to try this code, which I tested on python3.6 and worked:

```
for infile in infiles:
    print('Reading ' + infile)
    with open(os.path.join(args.downloaded_feats, infile), "r+t") as tsv_in_file:
        reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES)
        for item in reader:
            item['image_id'] = int(item['image_id'])
            item['num_boxes'] = int(item['num_boxes'])
            for field in ['boxes', 'features']:
                item[field] = np.frombuffer(base64.decodestring(item[field].encode()), 
                        dtype=np.float32).reshape((item['num_boxes'],-1))
            np.savez_compressed(os.path.join(args.output_dir+'_att', str(item['image_id'])), feat=item['features'])
            np.save(os.path.join(args.output_dir+'_fc', str(item['image_id'])), item['features'].mean(0))
            np.save(os.path.join(args.output_dir+'_box', str(item['image_id'])), item['boxes'])
```

where the changes are in line 38 and 44.

**Comment by faaizhashmi** [comment]
@husthuaan Thank you so much. Its works.
