### ISSUE TITLE
No such file: karpathy_test_resnet101_faster_rcnn_genome.tsv

### ISSUE THREAD

**Issue by VahidChahkandi** [husthuaan/AoANet#47]
Thank you for sharing your code.
Could you please help me on how to find these files? or where can I download them?
I got this error:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/bu_data/trainval/karpathy_test_resnet101_faster_rcnn_genome.tsv'`

probably I will need below files too:
trainval/karpathy_val_resnet101_faster_rcnn_genome.tsv',
'trainval/karpathy_train_resnet101_faster_rcnn_genome.tsv.0', 
'trainval/karpathy_train_resnet101_faster_rcnn_genome.tsv.1'

I will appreciate any help.

**Comment by State226** [comment]
How did you solve it

**Comment by hwbhwbgao** [comment]
> How did you solve it

https://github.com/peteanderson80/bottom-up-attention ,go to download it
