### ISSUE TITLE
where to get 5000 karpathy test split? 

### ISSUE THREAD

**Issue by LiJunnan1992** [husthuaan/AoANet#48]
Hi, thanks for the amazing code!

I'm new to this field, may I know where to get the 5000 test samples from karpathy's split? On COCO's official website, I can only find train2017 and val2017.

Thanks a lot!

**Comment by husthuaan** [comment]
You can access the preprocessed karpathy coco captions at http://cs.stanford.edu/people/karpathy/deepimagesent/caption_datasets.zip. The test split is also included.

Please check [data/README.md](https://github.com/husthuaan/AoANet/blob/master/data/README.md) for details about the dataset.

**Comment by LiJunnan1992** [comment]
thanks!
