### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by faaizhashmi** [husthuaan/AoANet#6]
**I tried to run "CUDA_VISIBLE_DEVICES=0 sh train.sh" for training but i get this error.**

Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from misc.rewards import init_scorer, get_self_critical_reward
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/misc/rewards.py", line 13, in <module>
    from pyciderevalcap.ciderD.ciderD import CiderD
ModuleNotFoundError: No module named 'pyciderevalcap'
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    from misc.rewards import init_scorer, get_self_critical_reward
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/misc/rewards.py", line 13, in <module>
    from pyciderevalcap.ciderD.ciderD import CiderD
ModuleNotFoundError: No module named 'pyciderevalcap'

**i have tried installing "conda install -c hcc pycocotools" this package but i am unable to install and this command gives this error** 
                                                                                                                                                       UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pycocotools -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:
Package python-dateutil conflicts for:
pycocotools -> matplotlib[version='>=2.1.0'] -> python-dateutil
Package ca-certificates conflicts for:
pycocotools -> python[version='>=3.6,<3.7.0a0'] -> ca-certificates
python=3.7 -> openssl[version='>=1.0.2p,<1.0.3a'] -> ca-certificates
Package pip conflicts for:
pycocotools -> python[version='>=3.6,<3.7.0a0'] -> pip
python=3.7 -> pip
Package certifi conflicts for:
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09']
pycocotools -> cython[version='>=0.27.3'] -> setuptools -> certifi[version='>=2016.09']
Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
pycocotools -> cython[version='>=0.27.3'] -> setuptools
Package wheel conflicts for:
python=3.7 -> pip -> wheel
pycocotools -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel

**any suggestions on resolving this error. please help.**

**Comment by husthuaan** [comment]
You probably don't have the required sub-modules [cider](https://github.com/ruotianluo/cider) and [coco-caption](https://github.com/ruotianluo/coco-caption) in your workspace. Checkout them ranther than install via conda, and follow the instructions to setup.

**Comment by faaizhashmi** [comment]
@husthuaan **thanks i have forget to download these sub modules now it work but giving this error now**

DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
Read data: 0.6928925514221191
iter 0 (epoch 0), train_loss = 6.829, time/batch = 0.954
Read data: 0.11802101135253906
Save ckpt on exception ...
model saved to log/log_aoanet/model.pth
Save ckpt done.
Traceback (most recent call last):
  File "train.py", line 169, in train
    model_out = dp_lw_model(fc_feats, att_feats, labels, masks, att_masks, data['gts'], torch.arange(0, len(data['gts'])), sc_flag)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/misc/loss_wrapper.py", line 20, in forward
    loss = self.crit(self.model(fc_feats, att_feats, labels, att_masks), labels[:,1:], masks[:,1:])
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/CaptionModel.py", line 34, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/AttModel.py", line 126, in _forward
    p_fc_feats, p_att_feats, pp_att_feats, p_att_masks = self._prepare_feature(fc_feats, att_feats, att_masks)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/AoAModel.py", line 211, in _prepare_feature
    att_feats = self.refiner(att_feats, att_masks)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/AoAModel.py", line 124, in forward
    x = layer(x, mask)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/AoAModel.py", line 111, in forward
    x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, mask))
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/TransformerModel.py", line 101, in forward
    return x + self.dropout(sublayer(self.norm(x)))
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/AoAModel.py", line 111, in <lambda>
    x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, mask))
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/models/AoAModel.py", line 86, in forward
    x = x.transpose(1, 2).contiguous() \
RuntimeError: CUDA out of memory. Tried to allocate 10.62 MiB (GPU 0; 2.95 GiB total capacity; 1.92 GiB already allocated; 18.19 MiB free; 120.47 MiB cached)

Terminating BlobFetcher
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 146, in train
    init_scorer(opt.cached_tokens)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/misc/rewards.py", line 23, in init_scorer
    CiderD_scorer = CiderD_scorer or CiderD(df=cached_tokens)
  File "cider/pyciderevalcap/ciderD/ciderD.py", line 28, in __init__
    self.cider_scorer = CiderScorer(n=self._n, df_mode=self._df)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 80, in __init__
    pkl_file = cPickle.load(open(os.path.join('data', df_mode + '.p'),'rb'), **(dict(encoding='latin1') if six.PY3 else {}))
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco-train-idxs.p'
Terminating BlobFetcher

**before using bottom-up approach we have tried resnet approach but this same error occur when we were trying to train and with bottom-up approach we get the same error of CUDA out of memory. we have NVIDIA GTX 1060 (3GB memory). thus it required GPU with more memory?**

**Comment by husthuaan** [comment]
Yes, it requires more memory because of the refining module. `train-wo-refining.sh` requires less. You can also make `--rnn_size`, `--input_encoding_size` smaller so as to train the model on your GPU.

**Comment by faaizhashmi** [comment]
**@husthuaan i have set --rnn_size, --input_encoding_size to 512 but it gives this error:**

DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 57, in train
    assert vars(saved_model_opt)[checkme] == vars(opt)[checkme], "Command line argument and saved model disagree on '%s' " % checkme
AssertionError: Command line argument and saved model disagree on 'rnn_size' 
Terminating BlobFetcher
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 57, in train
    assert vars(saved_model_opt)[checkme] == vars(opt)[checkme], "Command line argument and saved model disagree on '%s' " % checkme
AssertionError: Command line argument and saved model disagree on 'rnn_size' 
Terminating BlobFetcher

**i have tried doing this before when i was trying to train using resnet approach but this gives the same error. so what should be the size of these two?**
**by the way how much GPU memory thus its require?**

**Comment by faaizhashmi** [comment]
@husthuaan I have change the size of rnn and input_encoding size to 512 from 1024. It has started training but then stop after some time because of CUDA out of memory error. Can you tell me what should be size of rnn and input_encoding according to our GPU(3GB) and how much GPU memory would be sufficient for this training to complete?

**Comment by husthuaan** [comment]
According to my experience, using the training script `train.sh` requires about 8GB GPU memory, while `train-wo-refining.sh` requires about 3GB (maybe a little more). 3GB GPU memory should be sufficient for  `train-wo-refining.sh`  if you set  `--rnn_size` and  `--input_encoding_size` to 512 (decrease them if still not works).

**Comment by faaizhashmi** [comment]
@husthuaan  as we have changed sizes 1024 to 512 and now we are using train_wo_refining. Will it affect the result?

**Comment by husthuaan** [comment]
@faaizhashmi It will.

**Comment by faaizhashmi** [comment]
@husthuaan **training successfully completes 1 epoch on 6000 iterations.   Then starts evaluations. When completed, gives this error.**
```
image 296759: a teddy bear is holding a teddy bear
evaluating validation preformance... -1/5000 (2.549190)
loading annotations into memory...
0:00:00.501229
creating index...
index created!
using 5000/5000 predictions
Loading and preparing results...     
DONE (t=0.02s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 307821 tokens at 759930.85 tokens per second.
PTBTokenizer tokenized 55094 tokens at 545484.58 tokens per second.
setting up scorers...
/home/faaiz/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 223, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/eval_utils.py", line 161, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/eval_utils.py", line 55, in language_eval
    cocoEval.evaluate()
  File "coco-caption/pycocoevalcap/eval.py", line 51, in evaluate
    (WMD(),   "WMD"),
  File "coco-caption/pycocoevalcap/wmd/wmd.py", line 17, in __init__
    self.model = gensim.models.KeyedVectors.load_word2vec_format(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'data', 'GoogleNews-vectors-negative300.bin'), binary=True)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1119, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/gensim/models/utils_any2vec.py", line 173, in _load_word2vec_format
    with utils.smart_open(fname) as fin:
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 453, in smart_open
    return open(uri, mode, ignore_ext=ignore_extension, transport_params=transport_params, **scrubbed_kwargs)
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 307, in open
    errors=errors,
  File "/home/faaiz/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 512, in _shortcut_open
    return _builtin_open(parsed_uri.uri_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/home/faaiz/Downloads/AoANet-master(Bottom up)/coco-caption/pycocoevalcap/wmd/data/GoogleNews-vectors-negative300.bin'
Terminating BlobFetcher
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 52, in train
    with open(os.path.join(opt.start_from, 'infos_'+opt.id+'.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'log/log_aoanet-wo-refinng/infos_aoanet-wo-refinng.pkl'
Terminating BlobFetcher

```

**Comment by faaizhashmi** [comment]
@husthuaan We used train_wo_refining. It successfully runs 1 epoch over 6000 iterations. Then it starts evaluation. Once completed, gives this error 

```
image 203138: a man in a kitchen with a refrigerator in the kitchen
image 296759: a teddy bear with a teddy bear and a stuffed teddy bear
evaluating validation preformance... -1/5000 (2.559475)
loading annotations into memory...
0:00:00.579296
creating index...
index created!
using 5000/5000 predictions
Loading and preparing results...     
DONE (t=0.02s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 307821 tokens at 728546.95 tokens per second.
PTBTokenizer tokenized 53019 tokens at 514423.09 tokens per second.
setting up scorers...
/home/faaiz/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
computing Bleu score...
{'testlen': 48020, 'reflen': 47751, 'guess': [48020, 43020, 38020, 33020], 'correct': [33280, 16787, 7241, 2886]}
ratio: 1.0056333898766308
Bleu_1: 0.693
Bleu_2: 0.520
Bleu_3: 0.372
Bleu_4: 0.259
computing METEOR score...
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 223, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/eval_utils.py", line 161, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/eval_utils.py", line 55, in language_eval
    cocoEval.evaluate()
  File "coco-caption/pycocoevalcap/eval.py", line 59, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 43, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 67, in _stat
    self.meteor_p.stdin.write(score_line+'\n')
BrokenPipeError: [Errno 32] Broken pipe
Terminating BlobFetcher

```

**Comment by husthuaan** [comment]
@faaizhashmi  This error occurs on some machines. Have a look at https://github.com/tylin/coco-caption/issues/17.

**Comment by faaizhashmi** [comment]
@husthuaan From the Issue given above tylin/coco-caption#17. We tried the first suggestion 

```
> It might be a problem of java.
> Try this:
> 
>     Install java on your linux system, if it wasn't installed.
>     In the initialization function of meteor.py:
> 
> def __init__(self):
>     self.meteor_cmd = ['java', '-jar', '-Xmx2G', METEOR_JAR, '-', '-', '-stdio', '-l', 'en', '-norm']
>     self.meteor_p = subprocess.Popen(' '.join(self.meteor_cmd),\     # change this line
>         cwd=os.path.dirname(os.path.abspath(__file__)), \
>         stdin=subprocess.PIPE, \
>         stdout=subprocess.PIPE, \
>         stderr=subprocess.PIPE,\
>         shell=True)
>         # Used to guarantee thread safety
>         self.lock = threading.Lock()
```
It did not give broken pipe error but gave this instead
```
image 203138: a man standing in front of a refrigerator in a kitchen
image 296759: a teddy bear with a teddy bear and a teddy bear
evaluating validation preformance... -1/5000 (2.585238)
loading annotations into memory...
0:00:00.447847
creating index...
index created!
using 5000/5000 predictions
Loading and preparing results...     
DONE (t=0.02s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 307821 tokens at 917630.90 tokens per second.
PTBTokenizer tokenized 54337 tokens at 494168.22 tokens per second.
setting up scorers...
/home/faaiz/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
computing Bleu score...
{'testlen': 49338, 'reflen': 48664, 'guess': [49338, 44338, 39338, 34338], 'correct': [33896, 17323, 7532, 3038]}
ratio: 1.0138500739766354
Bleu_1: 0.687
Bleu_2: 0.518
Bleu_3: 0.372
Bleu_4: 0.260
computing METEOR score...
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 223, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/eval_utils.py", line 161, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/home/faaiz/Downloads/AoANet-master(Bottom up)/eval_utils.py", line 55, in language_eval
    cocoEval.evaluate()
  File "coco-caption/pycocoevalcap/eval.py", line 59, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 40, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 64, in _stat
    self.meteor_p.stdin.write(score_line+'\n')
TypeError: a bytes-like object is required, not 'str'
Terminating BlobFetcher
```
 i tried another suggestion which was just to replace the line in initialization function of meteor.py:

> I had the same problem before as well (but I was using Python 3 version from this repo).
> My fix was adding the data file when running java cmd. Hope this helps.
> 
> self.meteor_cmd = ['java', '-jar', '-Xmx2G', METEOR_JAR, '-', '-', '-stdio', '-l', 'en', '-norm', '-a', 'data/paraphrase-en.gz']
>

**Comment by husthuaan** [comment]
This is weird. You can temporarily avoid computing these metrics by commenting these lines in `coco-caption/pycocoevalcap/eval.py`, line 45-52:
```
        scorers = [
            (Bleu(4), ["Bleu_1", "Bleu_2", "Bleu_3", "Bleu_4"]),
            # (Meteor(),"METEOR"),
            (Rouge(), "ROUGE_L"),
            (Cider(), "CIDEr"),
            (self.Spice, "SPICE"),
            # (WMD(),   "WMD"),
        ]
```

**Comment by faaizhashmi** [comment]
@husthuaan  Thank you for all the cooperation. We have successfully been able to run 34 epochs. Now our programs gives this error. 

```
Read data: 0.37630248069763184
iter 396504 (epoch 34), train_loss = 3.060, time/batch = 0.125
Terminating BlobFetcher
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocobu_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Traceback (most recent call last):
  File "train.py", line 275, in <module>
    train(opt)
  File "train.py", line 146, in train
    init_scorer(opt.cached_tokens)
  File "/home/faaiz/Downloads/AoANet-master_Bottom up/misc/rewards.py", line 23, in init_scorer
    CiderD_scorer = CiderD_scorer or CiderD(df=cached_tokens)
  File "cider/pyciderevalcap/ciderD/ciderD.py", line 28, in __init__
    self.cider_scorer = CiderScorer(n=self._n, df_mode=self._df)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 80, in __init__
    pkl_file = cPickle.load(open(os.path.join('data', df_mode + '.p'),'rb'), **(dict(encoding='latin1') if six.PY3 else {}))
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco-train-idxs.p'
Terminating BlobFetcher
```

We tried to find the file named  

> coco-train-idxs.p

. But we keep on ending up on the different coco datasets directories and pages. No file identical to this is found. Do you have any idea regarding this problem?

**Comment by husthuaan** [comment]
Please execute the following command to generate `coco-train-idxs.p`.
```
$ python scripts/prepro_ngrams.py --input_json data/dataset_coco.json --dict_json data/cocotalk.json --output_pkl data/coco-train --split train
```
Sorry for my negligence and I will update `README`. Thank you.

**Comment by faaizhashmi** [comment]
@husthuaan we were able to run 34 epochs and there was no error but only above file was missing. Does this means that training is done or we do we have to start over again after adding the file `coco-train-idxs.p`

**Comment by husthuaan** [comment]
The xe training stage is done. You don't need to start over again. The training script will load the history checkpoint.
