### ISSUE TITLE
AttentionEnsmeble

### ISSUE THREAD

**Issue by homelifes** [husthuaan/AoANet#8]
Hi. Thanks for your work!
May I know what is meant by AttentionEnsemble in your code and in your paper? What exactly is getting evaluated as an ensemble? Is it the same model trained with different initialization techniques?

**Comment by husthuaan** [comment]
Yes, you are right. We obtain an ensemble by training a number of same models which have diffrent initialized  parameters.

**Comment by homelifes** [comment]
Thanks!
