### ISSUE TITLE
Caption on single Image

### ISSUE THREAD

**Issue by hishamabutt** [husthuaan/AoANet#9]
@husthuaan great work there. i have been able to train the model following you instructions. Now can you please tell me how can I able to give a caption on single image using the model I have trained?

**Comment by husthuaan** [comment]
@hishamabutt You should creat a file `cocotalk_1image.json` in the same form as `cocotalk.json`, 
 copy `ix_to_word` to the file and specify `images`. After that, the content should be :
```json
{"ix_to_word": {"1": "a", "2": "man", ..., "10369": "UNK"}, "images": [{"split": "test", "file_path": "val2014\\COCO_val2014_000000391895.jpg", "id": 391895, "width": 640, "height": 360}]}
```
Replace the `id` with that of the image that you want to caption.
And excute the following command:
```bash
$ CUDA_VISIBLE_DEVICES=0 python eval.py --model log/log_aoanet_rl/model.pth --infos_path log/log_aoanet_rl/infos_aoanet.pkl --input_json cocotalk_1image.json  --dump_images 0 --dump_json 1 --num_images -1 --language_eval 0 --beam_size 2 --batch_size 1 --split test
```

**Comment by hishamabutt** [comment]
@husthuaan Thanks this work fine on coco images. But how can i try this model to give caption on random images from google?

**Comment by husthuaan** [comment]
@hishamabutt  For random images other than those from COCO, you need to extract the bottom-up features of them. See the instructions at https://github.com/peteanderson80/bottom-up-attention.

**Comment by hishamabutt** [comment]
@husthuaan sorry for the delay. but i have make an .npy files of freatures using 
https://github.com/violetteshev/bottom-up-features
now where sholud i put this file to get a caption on random image?

**Comment by husthuaan** [comment]
@hishamabutt You can put it anywhere you want, e.g. `data/test_fc, data/test_att`. Then specify these directories when runing `eval.py`: `python eval.py --input_json cocotalk_1image.json --input_fc_dir data/test_fc --input_att_dir data/test_att ...`.

**Comment by hishamabutt** [comment]
@husthuaan first i have to create a file cocotalk_1image.json like

`{"ix_to_word": {"1": "a", "2": "man", ..., "10369": "UNK"}, "images": [{"split": "test", "file_path": "randomImage/abc.jpg", "id": 391895, "width": 640, "height": 360}]}`

then if i have put the file in data/test_fc then

`CUDA_VISIBLE_DEVICES=0 python eval.py --model log/log_aoanet_rl/model.pth --infos_path log/log_aoanet_rl/infos_aoanet.pkl --input_json cocotalk_1image.json --input_fc_dir data/test_fc  --dump_images 0 --dump_json 1 --num_images -1 --language_eval 0 --beam_size 2 --batch_size 1 --split test`

correct me if i am wrong

**Comment by husthuaan** [comment]
@hishamabutt There are actually two directories, `data/test_fc, data/test_att`, where `fc ` is the mean pooling of `att`.

**Comment by hishamabutt** [comment]
@husthuaan so i have to specify both of the directories in the command like this  

`CUDA_VISIBLE_DEVICES=0 python eval.py --model log/log_aoanet_rl/model.pth --infos_path log/log_aoanet_rl/infos_aoanet.pkl --input_json cocotalk_1image.json --input_fc_dir data/test_fc --input_att_dir data/test_att --dump_images 0 --dump_json 1 --num_images -1 --language_eval 0 --beam_size 2 --batch_size 1 --split test`

even i have put my .npy file in either one of the directories?

**Comment by husthuaan** [comment]
@hishamabutt No, the two directories are different and you should have two files. `att` stores the bottom-up features of objects in the image, while `fc` is the mean pooling of `att`. Just have a look at the examples in `data/cocobu_fc, data/cocobu_att`.

**Comment by hishamabutt** [comment]
@husthuaan i have looked into the example. can you tell me how can i make these tow files using this
https://github.com/violetteshev/bottom-up-features
its only make .npy file.

**Comment by hishamabutt** [comment]
@husthuaan i have three files like `data/cocobu_fc, data/cocobu_att and data/cocobu_box` now should i run this 

`CUDA_VISIBLE_DEVICES=0 python eval.py --model log/log_aoanet_rl/model.pth --infos_path log/log_aoanet_rl/infos_aoanet.pkl --input_json cocotalk_1image.json --input_fc_dir data/test_fc --input_att_dir data/test_att --input_box_dir data/test_box --dump_images 0 --dump_json 1 --num_images -1 --language_eval 0 --beam_size 2 --batch_size 1 --split test`

and change the cocotalk_1image.json 

`{"ix_to_word": {"1": "a", "2": "man", ..., "10369": "UNK"}, "images": [{"split": "test", "file_path": "randomImage/abc.jpg", "id": abc, "width": 640, "height": 360}]}`

to get caption on random image?

**Comment by husthuaan** [comment]
I suppose so. Did you get any problem?

**Comment by hishamabutt** [comment]
@husthuaan thanks its work fine

**Comment by dinhanhx** [comment]
Shouldn't this be in some README files to let other know the way?
